#!/bin/bash
# aggregate-stats.sh - GitHub Actions용 리포 통계 수집
# Usage: aggregate-stats.sh [daily|weekly|monthly]

set -euo pipefail

MODE=${1:-daily}
DATE=$(date -u +%Y-%m-%d)
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$REPO_ROOT/config/tracked-repos.json"
OUTPUT_DIR="$REPO_ROOT/data/reviews/$MODE"
OUTPUT_FILE="$OUTPUT_DIR/${DATE}-stats-raw.md"

mkdir -p "$OUTPUT_DIR"

# Determine date range
case $MODE in
  daily)
    SINCE=$(date -u -d "1 day ago" +%Y-%m-%dT00:00:00Z 2>/dev/null || date -u -v-1d +%Y-%m-%dT00:00:00Z)
    TITLE="Daily Stats"
    ;;
  weekly)
    SINCE=$(date -u -d "7 days ago" +%Y-%m-%dT00:00:00Z 2>/dev/null || date -u -v-7d +%Y-%m-%dT00:00:00Z)
    TITLE="Weekly Stats"
    ;;
  monthly)
    SINCE=$(date -u -d "30 days ago" +%Y-%m-%dT00:00:00Z 2>/dev/null || date -u -v-30d +%Y-%m-%dT00:00:00Z)
    TITLE="Monthly Stats"
    ;;
  *)
    echo "Usage: $0 [daily|weekly|monthly]"
    exit 1
    ;;
esac

cat > "$OUTPUT_FILE" << EOF
---
type: stats-raw
mode: $MODE
date: $DATE
since: $SINCE
generated_by: github-actions
---

# $TITLE - $DATE

> Auto-generated by GitHub Actions. AI review pending.

EOF

# Read tracked repos
if [ ! -f "$CONFIG" ]; then
  echo "[ERROR] Config not found: $CONFIG"
  exit 1
fi

REPOS=$(jq -r '.repos[]' "$CONFIG")

for REPO in $REPOS; do
  echo "## $REPO" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"

  # Get commits since date
  COMMITS=$(gh api "repos/$REPO/commits?since=$SINCE&per_page=100" --jq 'length' 2>/dev/null || echo "0")
  echo "- **Commits**: $COMMITS" >> "$OUTPUT_FILE"

  # Get commit details
  if [ "$COMMITS" -gt 0 ] 2>/dev/null; then
    echo "- **Recent commits**:" >> "$OUTPUT_FILE"
    gh api "repos/$REPO/commits?since=$SINCE&per_page=10" \
      --jq '.[] | "  - `\(.sha[0:7])` \(.commit.message | split("\n")[0]) (\(.commit.author.name))"' \
      2>/dev/null >> "$OUTPUT_FILE" || true
  fi

  # Get PRs
  PRS_MERGED=$(gh api "repos/$REPO/pulls?state=closed&sort=updated&direction=desc&per_page=30" \
    --jq "[.[] | select(.merged_at != null and .merged_at >= \"$SINCE\")] | length" 2>/dev/null || echo "0")
  PRS_OPENED=$(gh api "repos/$REPO/pulls?state=open&sort=created&direction=desc&per_page=30" \
    --jq "[.[] | select(.created_at >= \"$SINCE\")] | length" 2>/dev/null || echo "0")
  echo "- **PRs merged**: $PRS_MERGED" >> "$OUTPUT_FILE"
  echo "- **PRs opened**: $PRS_OPENED" >> "$OUTPUT_FILE"

  # Get issues
  ISSUES_CLOSED=$(gh api "repos/$REPO/issues?state=closed&since=$SINCE&per_page=30" \
    --jq "[.[] | select(.pull_request == null)] | length" 2>/dev/null || echo "0")
  ISSUES_OPENED=$(gh api "repos/$REPO/issues?state=open&since=$SINCE&per_page=30" \
    --jq "[.[] | select(.pull_request == null and .created_at >= \"$SINCE\")] | length" 2>/dev/null || echo "0")
  echo "- **Issues closed**: $ISSUES_CLOSED" >> "$OUTPUT_FILE"
  echo "- **Issues opened**: $ISSUES_OPENED" >> "$OUTPUT_FILE"

  echo "" >> "$OUTPUT_FILE"
done

echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "_AI review will be generated locally via sync-and-enrich.sh_" >> "$OUTPUT_FILE"

echo "[OK] Stats written to $OUTPUT_FILE"
