#!/bin/bash
# dev-review-cron.sh - 개발 회고 자동화 스크립트
# cron에서 호출하는 통합 스크립트
#
# 사용법: dev-review-cron.sh [daily|weekly|monthly]
#
# crontab 설정:
#   0 22 * * *   ~/Documents/Obsidian-0.1/00.\ Inbox/03.\ AI\ Agent/scripts/dev-review-cron.sh daily
#   0 21 * * 0   ~/Documents/Obsidian-0.1/00.\ Inbox/03.\ AI\ Agent/scripts/dev-review-cron.sh weekly
#   0 21 1 * *   ~/Documents/Obsidian-0.1/00.\ Inbox/03.\ AI\ Agent/scripts/dev-review-cron.sh monthly

set -euo pipefail

MODE=${1:-daily}
LOG_DIR="$HOME/.claude/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/dev-review-$(date +%Y%m%d-%H%M%S).log"

echo "[$(date)] Starting $MODE review..." | tee "$LOG_FILE"

# Claude Code CLI 경로 확인
CLAUDE_CMD=$(which claude 2>/dev/null || echo "$HOME/.claude/bin/claude")
if [ ! -x "$CLAUDE_CMD" ]; then
  echo "[ERROR] Claude CLI not found" | tee -a "$LOG_FILE"
  exit 1
fi

# 가장 최근 작업한 git 프로젝트 디렉토리로 이동
# (cron 환경에서는 HOME이 기본이므로)
LAST_PROJECT_DIR=$(cat "$HOME/.claude/session-backups/last_session.json" 2>/dev/null | jq -r '.cwd // empty' || echo "$HOME")
if [ -d "$LAST_PROJECT_DIR" ]; then
  cd "$LAST_PROJECT_DIR"
fi

case $MODE in
  daily)
    echo "[$(date)] Running daily review..." | tee -a "$LOG_FILE"
    $CLAUDE_CMD -p "$(cat "$HOME/.claude/commands/dev-daily.md" | sed 's/\$ARGUMENTS/auto-generated by cron/')" 2>&1 | tee -a "$LOG_FILE"
    ;;
  weekly)
    echo "[$(date)] Running weekly review..." | tee -a "$LOG_FILE"
    $CLAUDE_CMD -p "$(cat "$HOME/.claude/commands/dev-weekly.md" | sed 's/\$ARGUMENTS/auto-generated by cron/')" 2>&1 | tee -a "$LOG_FILE"
    ;;
  monthly)
    echo "[$(date)] Running monthly review..." | tee -a "$LOG_FILE"
    $CLAUDE_CMD -p "$(cat "$HOME/.claude/commands/dev-monthly.md" | sed 's/\$ARGUMENTS/auto-generated by cron/')" 2>&1 | tee -a "$LOG_FILE"
    ;;
  *)
    echo "[ERROR] Unknown mode: $MODE. Use daily|weekly|monthly" | tee -a "$LOG_FILE"
    exit 1
    ;;
esac

echo "[$(date)] $MODE review completed." | tee -a "$LOG_FILE"
